/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author peper
 */
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.*;
import java.io.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;




public class FormPerhitunganKata extends javax.swing.JFrame {
private boolean autoHitungAktif = false;

    /**
     * Creates new form FormPerhitunganKata
     */
    public FormPerhitunganKata() {
        initComponents();
        
        textArea.getDocument().addDocumentListener(new DocumentListener() {
    @Override
    public void insertUpdate(javax.swing.event.DocumentEvent e) {
        if (autoHitungAktif) hitungOtomatis();
    }

    @Override
    public void removeUpdate(javax.swing.event.DocumentEvent e) {
      if (autoHitungAktif) hitungOtomatis();
    }

    @Override
    public void changedUpdate(javax.swing.event.DocumentEvent e) {
        if (autoHitungAktif) hitungOtomatis();
    }
});
    }
    // Menjalankan perhitungan otomatis saat teks berubah
    

    private void hitungOtomatis() {
    String teks = textArea.getText().trim();
    if (teks.isEmpty()) {
        lblKata.setText("Kata : 0");
        lblKarakter.setText("Karakter : 0");
        lblKalimat.setText("Kalimat : 0");
        lblParagraf.setText("Paragraf : 0");
        return;
    }

    // Hitung karakter
    int jumlahKarakter = teks.length();

    // Hitung kata
    String[] kataArray = teks.split("\\s+");
    int jumlahKata = (teks.isEmpty()) ? 0 : kataArray.length;

    // Hitung kalimat
    String[] kalimatArray = teks.split("[.!?]+");
    int jumlahKalimat = 0;
    for (String s : kalimatArray) {
        if (!s.trim().isEmpty()) jumlahKalimat++;
    }

    // Hitung paragraf
    String[] paragrafArray = teks.split("\\n+");
    int jumlahParagraf = 0;
    for (String p : paragrafArray) {
        if (!p.trim().isEmpty()) jumlahParagraf++;
    }

    // Tampilkan hasil
    lblKata.setText("Kata : " + jumlahKata);
    lblKarakter.setText("Karakter : " + jumlahKarakter);
    lblKalimat.setText("Kalimat : " + jumlahKalimat);
    lblParagraf.setText("Paragraf : " + jumlahParagraf);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        lblJudul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        lbltks = new javax.swing.JLabel();
        lblKata = new javax.swing.JLabel();
        lblKarakter = new javax.swing.JLabel();
        lblKalimat = new javax.swing.JLabel();
        lblParagraf = new javax.swing.JLabel();
        lblCari = new javax.swing.JLabel();
        txtPencarian = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penghitung Kata (Feriadi)");
        setBackground(new java.awt.Color(255, 102, 0));

        panel1.setBackground(new java.awt.Color(220, 230, 245));

        lblJudul.setBackground(new java.awt.Color(50, 50, 50));
        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(25, 50, 100));
        lblJudul.setText("APLIKASI PENGHITUNG KATA");

        textArea.setBackground(new java.awt.Color(255, 255, 245));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(30, 30, 30));
        textArea.setLineWrap(true);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        lbltks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltks.setForeground(new java.awt.Color(40, 40, 60));
        lbltks.setText("Masukan Teks di kolom bawah ini :");

        lblKata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKata.setForeground(new java.awt.Color(20, 40, 80));
        lblKata.setText("Kata :");

        lblKarakter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKarakter.setForeground(new java.awt.Color(20, 40, 80));
        lblKarakter.setText("Karakter :");

        lblKalimat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKalimat.setForeground(new java.awt.Color(20, 40, 80));
        lblKalimat.setText("Kalimat :");

        lblParagraf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblParagraf.setForeground(new java.awt.Color(20, 40, 80));
        lblParagraf.setText("Paragraf :");

        lblCari.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblCari.setText("Masukan Kata");

        txtPencarian.setForeground(new java.awt.Color(20, 20, 20));

        btnCari.setBackground(new java.awt.Color(100, 149, 237));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnHitung.setBackground(new java.awt.Color(70, 130, 180));
        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("Hitung");
        btnHitung.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(46, 139, 87));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltks)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(lblKata)
                                        .addGap(90, 90, 90)
                                        .addComponent(lblKarakter))
                                    .addComponent(btnHitung))
                                .addGap(62, 62, 62)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSimpan)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(lblKalimat)
                                        .addGap(57, 57, 57)
                                        .addComponent(lblParagraf))))
                            .addComponent(lblCari)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblJudul)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblJudul)
                .addGap(49, 49, 49)
                .addComponent(lbltks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKata)
                    .addComponent(lblKarakter)
                    .addComponent(lblKalimat)
                    .addComponent(lblParagraf))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
   hitungOtomatis();
   autoHitungAktif = true;
  // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
     String teks = textArea.getText().toLowerCase();
String cari = txtPencarian.getText().toLowerCase();

if (cari.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Masukkan kata yang ingin dicari!");
    return;
}

int count = 0;
String[] kataArray = teks.split("\\s+");
for (String k : kataArray) {
    if (k.equals(cari)) {
        count++;
    }
}

JOptionPane.showMessageDialog(this, 
    "Kata \"" + cari + "\" ditemukan sebanyak " + count + " kali.");
   // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       try {
    JFileChooser chooser = new JFileChooser();
    int option = chooser.showSaveDialog(this);
    if (option == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        FileWriter fw = new FileWriter(file);

        fw.write("Hasil Penghitungan Kata\n");
        fw.write(lblKata.getText() + "\n");
        fw.write(lblKarakter.getText() + "\n");
        fw.write(lblKalimat.getText() + "\n");
        fw.write(lblParagraf.getText() + "\n");
        fw.close();

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
    }
} catch (IOException e) {
    JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
}
 // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPerhitunganKata().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKalimat;
    private javax.swing.JLabel lblKarakter;
    private javax.swing.JLabel lblKata;
    private javax.swing.JLabel lblParagraf;
    private javax.swing.JLabel lbltks;
    private java.awt.Panel panel1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField txtPencarian;
    // End of variables declaration//GEN-END:variables
}
